require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInStringInterpolation: true
  AllowParenthesesInChaining: true
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'config/routes/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/**/*.rb'

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/admin_controller.rb'

Lint/EmptyWhen:
  Exclude:
    - 'db/seeds.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/features/*'

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*'
