require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInStringInterpolation: true
  AllowParenthesesInChaining: true
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'
    - 'config/routes/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/EmptyWhen:
  Exclude:
    - 'db/seeds.rb'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/**/*.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/application.rb'

Performance/MethodObjectAsBlock:
  Exclude:
    - 'app/models/summary.rb'
    - 'app/services/update_form/parsed_params.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/features/*'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/*'

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - 'spec/queries/**/*'
    - 'spec/features/**/*'
 
RSpec/MessageSpies:
  Exclude:
    - 'spec/services/update_form_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/services/step_flow_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/jobs/schedule_job_spec.rb'
