version: '3.9'
services:

  redis:
    image: redis:6.0-alpine
    networks:
      - gtrp
    ports:
      - 6379:6379

  database:
    image: postgres:15-alpine
    networks:
      - gtrp
    environment:
      - POSTGRES_USER=gtrp
      - POSTGRES_PASSWORD=gtrp
      - POSTGRES_DB=get_an_international_relocation_payment_development
    ports:
      - 5432:5432

  app: &app
    build:
      context: .
      args:
        - COMMIT_SHA=shafoo
        - GOVUK_NOTIFY_API_KEY
        - GOVUK_NOTIFY_GENERIC_EMAIL_TEMPLATE_ID
    networks:
      - gtrp
    depends_on: [ database, redis ]
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://gtrp:gtrp@database/get_an_international_relocation_payment_development
      - REDIS_URL=redis://redis
      - RAILS_ENV=development
    env_file:
      - .env

  worker:
    <<: *app
    ports:
      - 3001:3001
    command: ./bin/worker-startup.sh
networks:
  gtrp:
