shared:
  schools:
    - headteacher_name
  applicants:
    - given_name
    - middle_name
    - family_name
    - email_address
    - phone_number
    - passport_number
  forms:
    - given_name
    - middle_name
    - family_name
    - email_address
    - phone_number
    - nationality
    - sex
    - passport_number
    - visa_type
    - address_line_1
    - address_line_2
    - city
    - postcode
    - school_headteacher_name
